#!/usr/bin/env node
/**
 * One-time credential setup. Saves to config/.env — loaded permanently on every start.
 *
 * Usage: npm run setup
 */
import crypto from "crypto";
import fs from "fs";
import path from "path";
import readline from "readline";
import { fileURLToPath } from "url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const configDir = path.join(root, "config");
const configPath = path.join(configDir, ".env");
const examplePath = path.join(configDir, ".env.example");

function ask(rl, question, { defaultValue = "", secret = false } = {}) {
  const hint = defaultValue ? ` (${defaultValue})` : "";
  return new Promise((resolve) => {
    rl.question(`${question}${hint}: `, (answer) => {
      const trimmed = answer.trim();
      resolve(trimmed || defaultValue);
    });
  });
}

async function verifyShopify(domain, token, apiVersion) {
  const url = `https://${domain}/admin/api/${apiVersion}/graphql.json`;
  const headers = { "Content-Type": "application/json" };
  if (token.startsWith("shpat_")) {
    headers["X-Shopify-Access-Token"] = token;
  } else {
    headers.Authorization = `Bearer ${token}`;
  }

  const response = await fetch(url, {
    method: "POST",
    headers,
    body: JSON.stringify({
      query: `query { shop { name myshopifyDomain currencyCode } }`,
    }),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status} ${response.statusText}`);
  }

  const data = await response.json();
  if (data.errors?.length) {
    throw new Error(data.errors.map((e) => e.message).join("; "));
  }
  return data.data.shop;
}

function writeConfig(lines) {
  fs.mkdirSync(configDir, { recursive: true });
  fs.writeFileSync(configPath, `${lines.join("\n")}\n`, { mode: 0o600 });
}

async function main() {
  console.log("\nShopify Discord Agent — one-time setup\n");
  console.log("Credentials are saved to config/.env and loaded on every start.");
  console.log("You only need to run this once (re-run to update credentials).\n");

  if (fs.existsSync(configPath)) {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const overwrite = await ask(rl, "config/.env already exists. Overwrite? (y/N)", { defaultValue: "n" });
    rl.close();
    if (overwrite.toLowerCase() !== "y") {
      console.log("\nKeeping existing config/.env. Start the stack with: npm run docker:up\n");
      process.exit(0);
    }
  }

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  const useMock = await ask(rl, "Use mock Shopify data? (y/N)", { defaultValue: "n" });
  const mockMode = useMock.toLowerCase() === "y";

  let shopifyDomain = "";
  let shopifyToken = "";

  if (!mockMode) {
    shopifyDomain = await ask(rl, "Shopify store domain (e.g. mystore.myshopify.com)");
    while (!shopifyDomain.includes(".myshopify.com")) {
      console.log("  Domain should look like: mystore.myshopify.com");
      shopifyDomain = await ask(rl, "Shopify store domain");
    }

    shopifyToken = await ask(rl, "Shopify Admin API token (shpat_...)", { secret: true });
    while (!shopifyToken.startsWith("shpat_")) {
      console.log("  Custom app tokens start with shpat_. See docs/shopify-setup.md");
      shopifyToken = await ask(rl, "Shopify Admin API token");
    }

    console.log("\nVerifying Shopify credentials...");
    try {
      const shop = await verifyShopify(shopifyDomain, shopifyToken, "2025-01");
      console.log(`  Connected: ${shop.name} (${shop.myshopifyDomain}) — ${shop.currencyCode}\n`);
    } catch (error) {
      console.error(`  Failed: ${error.message}`);
      console.error("  Fix credentials and run npm run setup again.\n");
      rl.close();
      process.exit(1);
    }
  }

  const discordToken = await ask(rl, "Discord bot token");
  if (!discordToken) {
    console.error("\nDISCORD_BOT_TOKEN is required. Create a bot at https://discord.com/developers/applications\n");
    rl.close();
    process.exit(1);
  }

  const readOnlyAnswer = await ask(rl, "Read-only mode? (hide write tools) (Y/n)", { defaultValue: "y" });
  const readOnly = readOnlyAnswer.toLowerCase() !== "n";

  const channelIds = await ask(
    rl,
    "Discord channel ID to allow (optional — run npm run discord:demo-setup later)",
    { defaultValue: "" }
  );

  const mcpApiKey = crypto.randomBytes(24).toString("hex");

  rl.close();

  const lines = [
    "# Generated by npm run setup — permanent credentials (do not commit)",
    `SHOPIFY_DOMAIN=${shopifyDomain}`,
    `SHOPIFY_ACCESS_TOKEN=${shopifyToken}`,
    "SHOPIFY_API_VERSION=2025-01",
    `SHOPIFY_MOCK_MODE=${mockMode}`,
    `SHOPIFY_READ_ONLY=${readOnly}`,
    "SHOPIFY_CLI_AUTH=false",
    "",
    `DISCORD_BOT_TOKEN=${discordToken}`,
    `DISCORD_ALLOWED_CHANNEL_IDS=${channelIds}`,
    "",
    "PORT=3000",
    `MCP_API_KEY=${mcpApiKey}`,
    "",
    "N8N_WEBHOOK_URL=http://localhost:5678/webhook/discord",
    "N8N_PORT=5678",
    "N8N_HOST=localhost",
    "TZ=UTC",
  ];

  writeConfig(lines);

  console.log("Saved credentials to config/.env\n");
  console.log("Next steps:");
  console.log("  1. npm run docker:up              # starts stack (auto-restarts on reboot)");
  console.log("  2. Open http://localhost:5678     # import workflow, add Vertex creds, activate");
  console.log("  3. npm run discord:demo-setup     # optional: create #store-ops channel");
  console.log("  4. npm run verify:production      # pre-flight check");
  console.log("  5. Message your bot in Discord\n");
  console.log("Credentials persist across docker compose down / up.");
  console.log("Only docker compose down -v resets n8n data.");
  console.log("Production hardening: docs/production-checklist.md\n");

  if (fs.existsSync(examplePath)) {
    // no-op; example stays for reference
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});